### ISSUE TITLE
__calc_multitrial uses wrong data dimension size

### ISSUE THREAD

**Issue by ikarmann** [dokato/connectivipy#30]
__calc_multitrial from ConnectAR defines the number of trials as:
`trials = data.shape[0]`
whereas the documentation states that the trial number is the third dimension, i.e.
`trials = data.shape[2]`
hence, it leads to an error if the no of channels is > than the no of trials.

**Comment by dokato** [comment]
Thanks @ikarmann for reporting this. This #31 should fix it. I also made dimensions of data more explicit in the documentation.
