### ISSUE TITLE
`connectivipy.aec` Module not found, install from source

### ISSUE THREAD

**Issue by christianhacker** [dokato/connectivipy#35]
Fixed by adding an `__init__.py` to `aec` submodule and adding `connectivipy.aec` to packages list in setup.py.

**Comment by dokato** [comment]
Thanks, @christianhacker for reporting that. What python version are you using?

**Comment by christianhacker** [comment]
Python 3.8 

While I'm here, I'd like permission to adapt some of your code for the [SCoT toolbox](https://github.com/scot-dev/scot), specifically the various methods for fitting MVAR models (e.g. Yule-Walker, Viera-Morf). Currently SCoT uses ridge regression to fit model coefficients. I'm working with the original devs to adapt SCoT to make it more compatible with mne-python (discussion [here](https://mne.discourse.group/t/causal-spectral-connectivity-measures-per-8691/2434)).

**Comment by dokato** [comment]
Oh shoot, that's something new I guess, I tested under 3.4. Thanks, I'll fix that!

Sure, of course! Happy to help if needed.

**Comment by dokato** [comment]
This should be fixed in v `0.3.7`
