### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by fishbacp** [dokato/connectivipy#40]
I'm incorporating connectivipy into some software I'm writing that will look at network connectivity measures and be appropriate for use in a clinical setting. All python is converted to .app and .exe using pyinstaller. The software uses MNE, tkinter, and pandas extensively.

The package will be free of course, and my academic institution will help me construct an appropriate legal disclaimer.  However, since I'm incorporating connectivipy, particular for MVAR construction, I'd like to know the appropriate citation you'd like me to use.

**Comment by dokato** [comment]
Thank you @fishbacp for asking, and apologies for the late reply. You caught me during vacation days and I somehow missed this notification.

As we don't have a dedicated paper around it, our preferred citation in the ACM References Format would be:
> Krzemiński D. Kamiński M. 2015. ConnectiviPy. https://github.com/dokato/connectivipy. (2022). 

Good luck with your software 👍
