### ISSUE TITLE
Python 3.11 ?

### ISSUE THREAD

**Issue by fishbacp** [dokato/connectivipy#41]
I've enjoyed using this package for a few years now, but I'm unable to install it on a Windows machine running Python 3.11. I know you've tested it with much earlier versions of Python, but I had it working fine on 3.9.9. Any chance I can easily correct the error below?

Typing pip3 install connectivipy returns a fairly long error,

```
  **Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.**
```

and ending with 

       **File "C:\Users\fishbacp\AppData\Local\Temp\pip-install-c7i1nbit\connectivipy_18c81df64274429a9b41c91627ce597c\connectivipy\data.py", line 7, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'**

I've installed numpy so that's not the issue.

**Comment by dokato** [comment]
Oh sorry about that, let me check what's happening.

**Comment by fishbacp** [comment]
Thanks so much. I should mention that pip list shows I do have numpy 1.24.3 installed.

**Comment by dokato** [comment]
Huh, sorry, but I couldn't really reproduce your error. Here are my steps starting from a clean python 3.11 environment:
```sh
$ conda create -n "py311" python=3.11.3 ipython
$ conda activate py311
$ conda install numpy
$ conda install matplotlib
$ conda install scipy
$ pip install git+https://github.com/dokato/connectivipy.git
```

BTW with `pip install connectivipy` it worked as well 🤔
